"""Add mailtype to group.

Revision ID: 009352d11348
Revises: 47c84830979f
Create Date: 2018-01-04 15:10:15.752618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from app import db
from app.models.group import Group

# revision identifiers, used by Alembic.
revision = '009352d11348'
down_revision = '47c84830979f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('mailtype', sa.Enum('none', 'mailinglist', 'mailbox'), nullable=False))
    for group in db.session.query(Group).all():
        if group.maillist is not None and group.maillist.strip() != '':
            group.mailtype = 'mailinglist'

    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'mailtype')
    # ### end Alembic commands ###
