"""add column to user: receive_information

Revision ID: 12b99e99f10
Revises: 40f1fd0d52
Create Date: 2015-07-18 11:49:41.032915

"""

# revision identifiers, used by Alembic.
revision = '12b99e99f10'
down_revision = '40f1fd0d52'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('receive_information', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'receive_information')
    ### end Alembic commands ###
