"""Add student_id_confirmed to user.

Revision ID: 18485381c9be
Revises: 776b0d9121b7
Create Date: 2018-06-13 13:45:44.390612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship

# revision identifiers, used by Alembic.
revision = '18485381c9be'
down_revision = '776b0d9121b7'

Base = declarative_base()
db = sa
db.Model = Base
db.relationship = relationship


def create_session():
    connection = op.get_bind()
    session_maker = sa.orm.sessionmaker()
    session = session_maker(bind=connection)
    db.session = session


def upgrade():
    create_session()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id_confirmed', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    create_session()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'student_id_confirmed')
    # ### end Alembic commands ###


# vim: ft=python
