"""Remove mollie shizzle

Revision ID: 18f253dd886
Revises: 1b2745bbb1d
Create Date: 2015-05-09 12:41:30.366101

"""

# revision identifiers, used by Alembic.
revision = '18f253dd886'
down_revision = '1b2745bbb1d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mollie_transaction_ibfk_2', 'mollie_transaction', type_='foreignkey')
    op.drop_column('mollie_transaction', 'paidDatetime')
    op.drop_column('mollie_transaction', 'expiredDatetime')
    op.drop_column('mollie_transaction', 'createdDatetime')
    op.drop_column('mollie_transaction', 'amount')
    op.drop_column('mollie_transaction', 'user_id')
    op.drop_column('mollie_transaction', 'description')
    op.drop_column('mollie_transaction', 'cancelledDatetime')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mollie_transaction', sa.Column('cancelledDatetime', mysql.DATETIME(), nullable=True))
    op.add_column('mollie_transaction', sa.Column('description', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('mollie_transaction', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('mollie_transaction', sa.Column('amount', mysql.FLOAT(), nullable=True))
    op.add_column('mollie_transaction', sa.Column('createdDatetime', mysql.DATETIME(), nullable=True))
    op.add_column('mollie_transaction', sa.Column('expiredDatetime', mysql.DATETIME(), nullable=True))
    op.add_column('mollie_transaction', sa.Column('paidDatetime', mysql.DATETIME(), nullable=True))
    op.create_foreign_key('mollie_transaction_ibfk_2', 'mollie_transaction', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
