from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

"""copernica_id to separate tables

Revision ID: 1eaf85d91ee
Revises: 48c16211f99
Create Date: 2016-11-12 13:55:00.093625

"""

# revision identifiers, used by Alembic.
revision = '1eaf85d91ee'
down_revision = '48c16211f99'


def upgrade():
    # commands auto generated by Alembic - please adjust! #
    op.create_table('mailing_list',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('modified', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('copernica_db_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id',
                                            name=op.f('pk_mailing_list')),
                    sqlite_autoincrement=True)
    op.create_table('mailing_list_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('modified', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('mailing_list_id', sa.Integer(), nullable=True),
                    sa.Column('copernica_user_id',
                              sa.Integer(),
                              nullable=True),
                    sa.Column('subscribed', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['mailing_list_id'],
                                            ['mailing_list.copernica_db_id'],
                                            name=op.f('fk_mailing_list_user' +
                                                      '_mailing_list_id' +
                                                      '_mailing_list')),
                    sa.ForeignKeyConstraint(['user_id'],
                                            ['user.id'],
                                            name=op.f('fk_mailing_list_user' +
                                                      '_user_id_user')),
                    sa.PrimaryKeyConstraint('id',
                                            name=op.f('pk_mailing_list_user')),
                    sqlite_autoincrement=True)
    op.drop_column('user', 'copernica_id')
    op.drop_column('user', 'receive_information')
    # end Alembic commands #


def downgrade():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('user',
                  sa.Column('receive_information',
                            mysql.TINYINT(display_width=1),
                            autoincrement=False,
                            nullable=True))
    op.add_column('user',
                  sa.Column('copernica_id',
                            mysql.INTEGER(display_width=11),
                            autoincrement=False,
                            nullable=True))
    op.drop_table('mailing_list_user')
    op.drop_table('mailing_list')
    # end Alembic commands #
