"""empty message

Revision ID: 40f1fd0d52
Revises: 3c540551b65
Create Date: 2015-06-13 17:06:59.167838

"""

# revision identifiers, used by Alembic.
revision = '40f1fd0d52'
down_revision = '3c540551b65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_form', sa.Column('terms', sa.String(length=4096), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_form', 'terms')
    ### end Alembic commands ###
