from alembic import op
import sqlalchemy as sa
"""Updated columns for dual-language

Revision ID: 11c83a1168c
Revises: 40f1fd0d52
Create Date: 2015-06-19 19:08:00.678224

"""

# revision identifiers, used by Alembic.
revision = '11c83a1168c'
down_revision = '40f1fd0d52'


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'name', new_column_name='nl_name', existing_type=sa.String(length=256))  # noqa
    op.alter_column('activity', 'description', new_column_name='nl_description', existing_type=sa.String(length=2048))  # noqa
    op.add_column('activity', sa.Column('en_description', sa.String(length=2048), nullable=True))  # noqa
    op.add_column('activity', sa.Column('en_name', sa.String(length=256), nullable=True))  # noqa
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'nl_name', new_column_name='name', existing_type=sa.String(length=256))  # noqa
    op.alter_column('activity', 'nl_description', new_column_name='description', existing_type=sa.String(length=256))  # noqa
    op.drop_column('activity', 'en_name')
    op.drop_column('activity', 'en_description')
    # end Alembic commands ###
