"""Add redirect model

Revision ID: 4a4eb48b62f
Revises: 18f253dd886
Create Date: 2015-05-09 14:23:34.237322

"""

# revision identifiers, used by Alembic.
revision = '4a4eb48b62f'
down_revision = '18f253dd886'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
