"""Removed the page_revision from news and created text columns

Revision ID: 1eb35537dac
Revises: 40f1fd0d52
Create Date: 2015-07-18 14:59:39.607943

"""

# revision identifiers, used by Alembic.
revision = '1eb35537dac'
down_revision = '40f1fd0d52'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('archive_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.drop_table('news_revision')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_revision',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('modified', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('instance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('end_time', sa.DATE(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='news_revision_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='news_revision_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('news')
    ### end Alembic commands ###
