""" Initial updates that were never done

Revision ID: 1b2745bbb1d
Revises: None
Create Date: 2015-05-09 11:32:23.175198

"""

# revision identifiers, used by Alembic.
revision = '1b2745bbb1d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programming_language')
    op.alter_column('page', 'type',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_constraint('page_ibfk_1', 'page', type_='foreignkey')
    op.drop_column('page', 'parent_id')
    op.drop_column('user', 'lectures_mail')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lectures_mail', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('page', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('page_ibfk_1', 'page', 'page', ['parent_id'], ['id'])
    op.alter_column('page', 'type', existing_type=mysql.VARCHAR(length=256),
                    nullable=False)
    op.create_table('programming_language',
                    sa.Column('id', mysql.INTEGER(display_width=11),
                              nullable=False),
                    sa.Column('created', mysql.DATETIME(), nullable=True),
                    sa.Column('modified', mysql.DATETIME(), nullable=True),
                    sa.Column('title', mysql.VARCHAR(length=256),
                              nullable=True), sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1', mysql_engine='InnoDB')
    ### end Alembic commands ###
