"""Rename mollie transaction to transcation.

Revision ID: fb7167c99f57
Revises: 4c55d2bbbe3
Create Date: 2016-11-24 15:59:58.994689

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fb7167c99f57'
down_revision = '4c55d2bbbe3'


def upgrade():
    # commands auto generated by Alembic - please adjust!
    op.rename_table('mollie_transaction', 'transaction')
    # end Alembic commands


def downgrade():
    # commands auto generated by Alembic - please adjust!
    op.rename_table('transaction', 'mollie_transaction')
    # end Alembic commands
