"""removed summaries.

Revision ID: c633060ef804
Revises: 58ec866f9f20
Create Date: 2017-11-11 15:19:34.206371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c633060ef804'
down_revision = '58ec866f9f20'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('modified', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('path', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('education_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_summary_course_id_course'),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], name='fk_summary_education_id_education'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
