"""removed deadline column pimpy

Revision ID: 299d2746edd
Revises: 40f1fd0d52
Create Date: 2015-07-18 13:21:16.172796

"""

# revision identifiers, used by Alembic.
revision = '299d2746edd'
down_revision = '40f1fd0d52'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pimpy_task', 'deadline')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pimpy_task', sa.Column('deadline', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
