"""Updated navigation module with dual language

Revision ID: 3769b81bfaf
Revises: aeceb6e193
Create Date: 2015-07-21 13:49:01.970788

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3769b81bfaf'
down_revision = 'aeceb6e193'


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.alter_column('nagivation_entry', 'title',
                    new_column_name='nl_title',
                    existing_type=sa.String(length=256))

    op.add_column('nagivation_entry',
                  sa.Column('en_title', sa.String(length=256), nullable=True))
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.alter_column('nagivation_entry', 'nl_title',
                    new_column_name='title',
                    existing_type=sa.String(length=256))
    op.drop_column('nagivation_entry', 'en_title')
    # end Alembic commands ###
