"""Add redirect model

Revision ID: 3c540551b65
Revises: 4a4eb48b62f
Create Date: 2015-05-09 14:25:49.826474

"""

# revision identifiers, used by Alembic.
revision = '3c540551b65'
down_revision = '4a4eb48b62f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('fro', sa.String(length=200), nullable=True),
    sa.Column('to', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fro'),
    sqlite_autoincrement=True
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redirect')
    ### end Alembic commands ###
