"""Added alumnus column

Revision ID: 41dd3272eb9
Revises: 2d257d93329
Create Date: 2016-08-10 18:29:03.035712

"""

# revision identifiers, used by Alembic.
revision = '41dd3272eb9'
down_revision = '2d257d93329'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alumnus', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'alumnus')
    ### end Alembic commands ###
