"""Updated user profile with copernica id

Revision ID: 4863452316a
Revises: 391b3fa1471
Create Date: 2016-01-28 15:38:19.335521

"""

# revision identifiers, used by Alembic.
revision = '4863452316a'
down_revision = '391b3fa1471'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('copernica_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_copernica_id'), 'user', ['copernica_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_copernica_id'), 'user', type_='unique')
    op.drop_column('user', 'copernica_id')
    ### end Alembic commands ###
