"""added test type to examination model

Revision ID: 49f0e0933ec
Revises: 391b3fa1471
Create Date: 2016-02-13 13:53:07.374136

"""

# revision identifiers, used by Alembic.
revision = '49f0e0933ec'
down_revision = '391b3fa1471'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examination', sa.Column('test_type', sa.Enum('Mid-term', 'End-term', 'Retake', 'Unknown'), server_default='Unknown', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examination', 'test_type')
    ### end Alembic commands ###
