"""Add address fields to user

Revision ID: 4d1a5fb71db
Revises: bef47d0853
Create Date: 2015-10-10 16:56:57.670618

"""

# revision identifiers, used by Alembic.
revision = '4d1a5fb71db'
down_revision = 'bef47d0853'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('zip', sa.String(length=8), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    ### end Alembic commands ###
