"""Removing start date, not needed for news

Revision ID: 4f0a2786b8c
Revises: 4b16f25315
Create Date: 2015-06-19 14:42:54.907538

"""

# revision identifiers, used by Alembic.
revision = '4f0a2786b8c'
down_revision = '4b16f25315'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'begin_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('begin_time', sa.DATE(), nullable=True))
    ### end Alembic commands ###
