"""added "open for new members" boolean to committee_revision.

Revision ID: 501bbf4c4770
Revises: b8cea80e0a3a
Create Date: 2017-08-15 12:08:12.642545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501bbf4c4770'
down_revision = 'b8cea80e0a3a'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committee_revision', sa.Column('open_new_members', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committee_revision', 'open_new_members')
    ### end Alembic commands ###
