"""disable_user

Revision ID: 5088a7fdf2
Revises: 391b3fa1471
Create Date: 2016-02-13 14:28:37.929236

"""

# revision identifiers, used by Alembic.
revision = '5088a7fdf2'
down_revision = '391b3fa1471'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    ### end Alembic commands ###
