"""Add maillist migrations

Revision ID: 54b3b06f09
Revises: 4013f6bd029
Create Date: 2015-07-18 15:45:45.226861

"""

# revision identifiers, used by Alembic.
revision = '54b3b06f09'
down_revision = '4013f6bd029'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('maillist', sa.String(length=100), nullable=True))
    op.create_unique_constraint(op.f('uq_group_maillist'), 'group', ['maillist'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_group_maillist'), 'group', type_='unique')
    op.drop_column('group', 'maillist')
    ### end Alembic commands ###
