"""add final minutes to alv.

Revision ID: a419497ed341
Revises: c633060ef804
Create Date: 2017-11-27 15:11:54.517391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a419497ed341'
down_revision = 'c633060ef804'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alv', sa.Column('minutes_file_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alv', 'minutes_file_id')
    # ### end Alembic commands ###
