"""Change File table for hashfs.

Revision ID: adbd033b0dcd
Revises: 0563ce5ca262
Create Date: 2018-03-10 14:04:06.216924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adbd033b0dcd'
down_revision = '0563ce5ca262'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'name', new_column_name='display_name', existing_type=sa.String(length=200))
    op.add_column('file', sa.Column('category', sa.Enum('UPLOADS', 'EXAMINATION', 'ACTIVITY_PICTURES', 'ALV_DOCUMENT', 'COMPANY_LOGO', 'USER_AVATAR', name='filecategory'), nullable=False))
    op.add_column('file', sa.Column('extension', sa.String(length=20), nullable=False))
    op.add_column('file', sa.Column('hash', sa.String(length=200), nullable=False))
    op.create_unique_constraint(op.f('uq_file_display_name'), 'file', ['display_name'])
    op.drop_index('uq_file_name', table_name='file')
    op.drop_constraint('file_ibfk_1', 'file', type_='foreignkey')
    op.drop_column('file', 'page_id')
    # op.drop_column('file', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'display_name', new_column_name='name', existing_type=sa.String(length=200))
    op.add_column('file', sa.Column('page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('file_ibfk_1', 'file', 'page', ['page_id'], ['id'])
    op.create_index('uq_file_name', 'file', ['name'], unique=True)
    op.drop_constraint(op.f('uq_file_display_name'), 'file', type_='unique')
    op.drop_column('file', 'hash')
    op.drop_column('file', 'extension')
    op.drop_column('file', 'category')
    # ### end Alembic commands ###
