"""Removed the extra column used for mollie description.

Revision ID: b42628364441
Revises: f8fcd4bb38cc
Create Date: 2017-03-05 10:14:07.942708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b42628364441'
down_revision = 'f8fcd4bb38cc'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_form', 'transaction_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_form',
                  sa.Column('transaction_description',
                            mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
